version: '3.1'

services:
  web-crm:
    container_name: ikon-crm
    image: odoo:16.0
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8042:8042"
    volumes:
      - ./debian/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
    command: sh -c "pip install openpyxl && pip install graphql-server && pip install graphene && pip install odoorpc && pip install wkhtmltopdf && exec odoo && tail -f /dev/null"

  db:
    container_name: db
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5442:5432"
    expose:
      - 5442:5442
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-crm-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-crm-db-data:
