version: '3.1'

services:
  web-crm:
    container_name: ikon-odoo
    image: odoo:16.0
    platform: linux/x86_64
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8042:8042"
    volumes:
      - ./debian/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons

  db:
    platform: linux/x86_64
    container_name: ikon-db
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5442:5432"
    expose:
      - 5442:5442
    environment:
      - POSTGRES_USER=ikon
      - POSTGRES_PASSWORD=ikon
      - POSTGRES_DB=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-crm-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-crm-db-data: